#acproject:
#  qiniu:
#    accessKey: 7xIbD6ObAiy8HmF-iNRzKmne5KZ9LcKJakUm_oMf
#    secretKey: wN0G09ufezIbc7xHqElHRIWHuUX1a19r92qooRgp
#    domain: qiniu.touchdot.top
#    bucketName: pingan
#    zone:
#    prefix: