spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security_flux_demo?characterEncoding=utf8&useSSL=false&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 60000
      connection-timeout: 30000
      connection-test-query: SELECT 'x'
  redis:
    #redis?????(???0)
    database: 7
    #redis?????ip or ??
    host: 127.0.0.1
    #redis?????
    port: 6379
    #redis????? abcpoiu1029
    password:
    #??lettue???
    lettuce:
      pool:
        #redis????????(????????) ???8
        max-active: -1
        #redis???????????(????????) ???-1
        max-wait: -1
        #redis?????????? ???8
        max-idle: 500
        #redis?????????? ???0
        min-idle: 100
    #redis??
    timeout: 30000
  cache:
    type: redis
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      resolve-lazily: false
      #file-size-threshold: 0
      #location:
  lifecycle:
    timeout-per-shutdown-phase: 25s
#acproject ??????
acproject:
  webflux:
    filter:
      xss:
        enabled: false
    miss-field: true
    static:
      enable: true
      type: DEFALUT
  cache:
    key:
      name: SECURITY_FLUX_DEMO
  redis:
    expire:
      time: 86400
  security:
    expire: 2419200
    secret: touch_security_secret_key_by_jane
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    # ??????
    db-config:
      # ???
      logic-not-delete-value: 1
      # ???
      logic-delete-value: 0
      #????
      id-type: auto
#      insert-strategy: IGNORED
#????
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  # port:
  port: 8080
  error:
    include-exception: true
  shutdown: graceful





