spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/security_flux_demo?characterEncoding=utf8&useSSL=false&autoReconnect=true&allowMultiQueries=true&rewriteBatchedStatements=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5
      min-idle: 5
      max-active: 5
      max-wait: 60000
      keep-alive: true
      keep-alive-between-time-millis: 600000
      time-between-eviction-runs-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      pool-prepared-statements: true
      # ?????????filters????????sql?????
      #'wall'??????SpringBoot???log4j?????log4j2
      filters: stat,wall,log4j2
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: true
      # ??connectProperties?????mergeSql????SQL??
      # ??StatFilter
      web-stat-filter:
        enabled: false
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        url-pattern: "/druid/*"
        #????ip
        #       allow: 127.0.0.1
        login-username: admin
        login-password: 123456
        #????ip
        #                deny: 192.168.1.102
        #??????
        #??
        enabled: false
        reset-enable: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  redis:
    #redis?????(???0)
    database: 7
    #redis?????ip or ??
    host: 127.0.0.1
    #redis?????
    port: 6379
    #redis????? abcpoiu1029
    password:
    #??lettue???
    lettuce:
      pool:
        #redis????????(????????) ???8
        max-active: -1
        #redis???????????(????????) ???-1
        max-wait: -1
        #redis?????????? ???8
        max-idle: 500
        #redis?????????? ???0
        min-idle: 100
    #redis??
    timeout: 30000
  cache:
    type: redis
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      resolve-lazily: false
      #file-size-threshold: 0
      #location:
  lifecycle:
    timeout-per-shutdown-phase: 25s
#acproject ??????
acproject:
  webflux:
    filter:
      xss:
        enabled: false
    miss-field: true
    static:
      enable: true
      type: DEFALUT
  cache:
    key:
      name: SECURITY_FLUX_DEMO
  redis:
    expire:
      time: 86400
  security:
    expire: 2419200
    secret: touch_security_secret_key_by_jane
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    # ??????
    db-config:
      # ???
      logic-not-delete-value: 1
      # ???
      logic-delete-value: 0
      #????
      id-type: auto
#      insert-strategy: IGNORED
#????
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  # port:
  port: 8080
  error:
    include-exception: true
  shutdown: graceful





