#redis
spring:
  datasource:
    url: jdbc:mysql://111.231.78.111:3306/security_flux_demo?characterEncoding=utf8&useSSL=false&serverTimezone=CTT&rewriteBatchedStatements=true
    username: root
    #生产环境
    password: root
    #测试环境
    #    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    #redis数据库索引(默认为0)
    database: 15
    #redis数据库地址ip or 域名
    host: localhost
    #redis数据库端口
    port: 6379
    #redis数据库密码
    password:
    #使用lettue连接池
    lettuce:
      pool:
        #redis连接池最大连接数(负值表示没有限制) 默认为8
        max-active: -1
        #redis连接池最大阻塞等待时间(负值表示没有限制) 默认为-1
        max-wait: -1
        #redis连接池最大空闲连接数 默认为8
        max-idle: 500
        #redis连接池最小空闲连接数 默认为0
        min-idle: 100
    #redis超时
    timeout: 30000
  cache:
    type: redis
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB
      resolve-lazily: false
      #file-size-threshold: 0
      #location:
#acproject 自定义属性集
acproject:
  redis:
    expire:
      time: 86400

mybatis:
  typeAliasesPackage: xyz.acproject.security_demo
  # mapper.xml文件所在位置，我放到了resources下面
  mapperLocations: classpath*:mapper/*.xml

#编码格式
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  tomcat:
    uri-encoding: UTF-8
  port: 8085
  error:
    include-exception: true
